# Generated by Django 5.1.7 on 2025-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
            ],
        ),
    ]
